# Generated by Django 3.2 on 2021-05-08 09:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210507_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=True, editable=True, populate_from='name_book'),
        ),
    ]
