# Generated by Django 3.2 on 2021-05-08 10:06

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug_chapter',
            field=autoslug.fields.AutoSlugField(default=True, editable=False, populate_from=models.CharField(max_length=100)),
        ),
    ]
