# Generated by Django 3.2 on 2021-05-08 11:37

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_chapter_slug_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='slug_chapter',
            field=autoslug.fields.AutoSlugField(default=True, editable=True, populate_from=models.CharField(max_length=100)),
        ),
    ]
