# Generated by Django 3.2 on 2021-05-08 11:38

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_chapter_slug_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name_book'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug_chapter',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from=models.CharField(max_length=100)),
        ),
    ]
