# Generated by Django 3.2 on 2021-05-08 11:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210508_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='slug_chapter',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name_chapter'),
        ),
    ]
