# Generated by Django 3.2 on 2021-05-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_chapter_slug_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='slug_chapter',
            new_name='slug',
        ),
    ]
