# Generated by Django 3.2 on 2021-05-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_slug_chapter_chapter_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='slug',
            new_name='slug_chapter',
        ),
    ]
